language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libinklevel5
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
